### ISSUE TITLE
The training model is irresponsive when running  ' for i,pred in enumerate(train_loader) '

### ISSUE THREAD

**Issue by chalth** [chenghao-shi/MDGAT-matcher#3]
HI, when i tried to train the model,  the training model is irresponsive when running  ' for i, pred in enumerate(train_loader) ', do you know the reason?

  0%|                                                         | 0/15223 [04:43<?, ?it/s]^C

**Comment by chenghao-shi** [comment]
Hi,






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenghao-shi/MDGAT-matcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 晚上7:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chenghao-shi/MDGAT-matcher] The training model is irresponsive when running  ' for i,pred in enumerate(train_loader) ' (Issue #3)





 
HI, when i tried to train the model,  the training model is irresponsive when running  ' for i, pred in enumerate(train_loader) ', do you know the reason?
 
0%|                                                         | 0/15223 [04:43<?, ?it/s]^C
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenghao-shi** [comment]
Hi,


Thanks for using. There should be some errors loading the data.&nbsp;Did you make changes in the 'load_data.py'? Please give more details.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenghao-shi/MDGAT-matcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 晚上7:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chenghao-shi/MDGAT-matcher] The training model is irresponsive when running  ' for i,pred in enumerate(train_loader) ' (Issue #3)





 
HI, when i tried to train the model,  the training model is irresponsive when running  ' for i, pred in enumerate(train_loader) ', do you know the reason?
 
0%|                                                         | 0/15223 [04:43<?, ?it/s]^C
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chalth** [comment]
Thanks for your reply, i have changed the  keypoints_path and  txt_path , and the following information occurred when i interrupt the training:

 0%|          | 0/15223 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/user/ch/MDGAT-matcher-main/train.py", line 226, in <module>
    for i, pred in enumerate(train_loader):
  File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/ch/MDGAT-matcher-main/load_data.py", line 202, in __getitem__
    kp1 = np.vstack((kp1[:(kp1_num-len(kp1))], kp1))
  File "<__array_function__ internals>", line 6, in vstack
  File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/numpy/core/shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
KeyboardInterrupt
  0%|          | 0/15223 [00:09<?, ?it/s]

Process finished with exit code 1

**Comment by chenghao-shi** [comment]
You might need to set the ensure_kpts_num to False. Sorry for the bug.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenghao-shi/MDGAT-matcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月11日(星期六) 晚上7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenghao-shi/MDGAT-matcher] The training model is irresponsive when running  ' for i,pred in enumerate(train_loader) ' (Issue #3)





 
Thanks for your reply, i have changed the  keypoints_path and  txt_path , and the following information occurred when i interrupt the training:
 
0%|          | 0/15223 [00:00<?, ?it/s]Traceback (most recent call last):
 File "/home/user/ch/MDGAT-matcher-main/train.py", line 226, in 
 for i, pred in enumerate(train_loader):
 File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/tqdm/std.py", line 1081, in iter
 for obj in iterable:
 File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in next
 data = self._next_data()
 File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
 data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
 File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in 
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/home/user/ch/MDGAT-matcher-main/load_data.py", line 202, in getitem
 kp1 = np.vstack((kp1[:(kp1_num-len(kp1))], kp1))
 File "<array_function internals&gt;", line 6, in vstack
 File "/home/user/anaconda3/envs/gmr3/lib/python3.7/site-packages/numpy/core/shape_base.py", line 282, in vstack
 return _nx.concatenate(arrs, 0)
 File "<array_function internals&gt;", line 6, in concatenate
 KeyboardInterrupt
 0%|          | 0/15223 [00:09<?, ?it/s]
 
Process finished with exit code 1
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chalth** [comment]
Thanks! It does work!
